# Linear Algebra Assignment

**Instructions:**
- Read each question carefully before answering.
- For **written/conceptual** questions, double-click the answer cell below the question and type your response.
- For **coding** questions, write your solution in the code cell provided.
- Run all code cells before submitting — make sure there are no errors.
- When done, click **"Save in GitHub to keep changes"** at the top to submit.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [1]:
# Run this cell before starting — do not modify
import numpy as np

---
## Q2 — Matrix Transformations

You are given the following matrix:

$$A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$$

And the following vectors:

```
v1 = [1, 0]
v2 = [0, 1]
v3 = [1, 1]
v4 = [-2, 4]
```

### Q2 Part (i) — Geometric Interpretation

**Without running any code**, predict what happens when you multiply matrix `A` by each of the vectors above.
Explain **geometrically** what the matrix is doing to each vector — not just what the numbers become.

A*v1=1st coloum of A
A*v2=2st coloum of A
A*v3=more tilted to x toward x axis=[2,3]T-->tranverse
A*v4=[-4,12]T

### Q2 Part (ii) — Respond to a Classmate

A classmate says:
> *"Matrix multiplication is just a complicated way to multiply numbers — it doesn't mean anything visually."*

Using your results from Part (i), write **3–4 sentences** proving them wrong.


*Write your answer here (double-click to edit this cell)*

matrix multiplication is geometric transformation of space, not just calculation.

Matrix multiplication is not just about numbers; it is like a visual command for an image or graph. Multiplying by this matrix $A$ tells the computer to stretch everything horizontally (sideways) by 2 times, and vertically (up-down) by 3 times. It physically changes how vectors look on a screen, proving that matrices are actually visual tools

### Q2 Part (iii) — NumPy Function

Write a NumPy function that:
- Takes **any 2×2 matrix** and **any 2D vector** as inputs
- Returns the **transformed vector**
- Prints a **one-line description** of how the x and y components individually change

Test your function on matrix `A` and all four vectors above.

In [2]:
# Input — do not modify
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])


In [3]:
# Write your code here:
def transform_vector(matrix, vector):
    # 1. Matrix multiplication kiya
    transformed = matrix @ vector

    # 2. Diagonal values se scaling change check ki
    scale_x = matrix[0, 0]
    scale_y = matrix[1, 1]

    # 3. One-line simple description print kiya
    print(f"X changes by factor of {scale_x} and Y changes by factor of {scale_y}")

    return transformed

print("Testing v1:")
print("Result:", transform_vector(A, v1))

print("\nTesting v2:")
print("Result:", transform_vector(A, v2))

print("\nTesting v3:")
print("Result:", transform_vector(A, v3))

print("\nTesting v4:")
print("Result:", transform_vector(A, v4))

Testing v1:
X changes by factor of 2 and Y changes by factor of 3
Result: [2 0]

Testing v2:
X changes by factor of 2 and Y changes by factor of 3
Result: [0 3]

Testing v3:
X changes by factor of 2 and Y changes by factor of 3
Result: [2 3]

Testing v4:
X changes by factor of 2 and Y changes by factor of 3
Result: [-4 12]


---
## Q3 — Tiny Recommendation System

Each user's taste is represented as a vector of 4 scores across 4 genres — **action, romance, thriller, comedy** — all between 0 and 1.

```
User A: [0.9, 0.1, 0.8, 0.2]
User B: [0.1, 0.9, 0.2, 0.8]
User C: [0.8, 0.2, 0.9, 0.1]
User D: [0.5, 0.5, 0.5, 0.5]
```

### Q3 Part (i) — Similarity Matrix

Compute the **full similarity matrix** — every user's similarity score against every other user — using only a **single NumPy operation** (no loops).

What linear algebra concept makes this possible in one line?

In [4]:
# Input — do not modify
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])


In [5]:
# Write your code here:
similarity_matrix = users @ users.T

print(similarity_matrix)

[[1.5  0.5  1.48 1.  ]
 [0.5  1.5  0.52 1.  ]
 [1.48 0.52 1.5  1.  ]
 [1.   1.   1.   1.  ]]


**What linear algebra concept makes this possible in one line?**


*Write your answer here (double-click to edit this cell)*

### Q3 Part (ii) — Reason About User D

User D has **equal scores** across all genres.

Before computing anything, reason through: will User D's similarity score with every other user be identical? **Why or why not?** Then verify with code.

*Write your answer here (double-click to edit this cell)*

In [10]:
# Write your code here:
print("User D's similarity scores with all users:", similarity_matrix[3])

User D's similarity scores with all users: [1. 1. 1. 1.]


### Q3 Part (iii) — The Problem with Raw Dot Products

A senior engineer tells you:
> *"Raw dot products are a bad measure of similarity — you need to normalize."\*

1. What is the **problem** with raw dot products?
2. Construct a **specific example using NumPy** that demonstrates the flaw.
3. Fix it.

> **Hint:** Take a user with scores `[1.8, 0.2, 1.6, 0.4]`

*Write your answer here (double-click to edit this cell)*

In [13]:
# Write your code here:
user_A = np.array([0.9, 0.1, 0.8, 0.2])
user_scaled = np.array([1.8, 0.2, 1.6, 0.4])

dot_self = np.dot(user_A, user_A)
dot_scaled = np.dot(user_A, user_scaled)

print("User A dot product with self:", dot_self)
print("User A dot product with over-scaled user:", dot_scaled)


norm_A = np.linalg.norm(user_A)
norm_scaled = np.linalg.norm(user_scaled)

cosine_sim = np.dot(user_A, user_scaled) / (norm_A * norm_scaled)

print("Normalized Similarity score:", cosine_sim)


User A dot product with self: 1.5000000000000002
User A dot product with over-scaled user: 3.0000000000000004
Normalized Similarity score: 1.0


### Q3 Part (iv) — Most Similar Users

After normalizing, which **two users are most similar**?

Does that match your intuition from just reading the vectors?

What does it mean in plain language — what do these two users have in common?

> **Note:** A similarity score is just a number that tells you **how alike two things are**.

*Write your answer here (double-click to edit this cell)*

In [14]:
# Write your code here:
norms = np.linalg.norm(users, axis=1, keepdims=True)

normalized_users = users / norms
cosine_matrix = normalized_users @ normalized_users.T

print(cosine_matrix.round(4))

[[1.     0.3333 0.9867 0.8165]
 [0.3333 1.     0.3467 0.8165]
 [0.9867 0.3467 1.     0.8165]
 [0.8165 0.8165 0.8165 1.    ]]


---

## 🎉 Submission Complete!

Make sure all code cells are run and all written answers are filled in, then click **"Save in GitHub to keep changes"** at the top.